### ISSUE TITLE
README should read like a tutorial

### ISSUE THREAD

**Issue by mateoclarke** [open-austin/atx-citysdk-js#6]

**Comment by mateoclarke** [comment]
Just finished a first pass on the README tutorial documentation. I think running through importing another city's data will inform some additions (My next step). @jmeisel, I'll throw it to you for any edit suggestions

**Comment by jgravois** [comment]
just pulled from `master` and it looks like the awesome new readme assumes the integration of changes from #7 that haven't been merged yet.

since we're planning on demoing today.  please let me know if it'd be helpful for me to amend the tutorial instructions to explain what's required currently.  as an alternative, i could also probably put together and link to a quick gist (to help clarify temporarily).

**Comment by mateoclarke** [comment]
We should have the new build system merged in by 3. Thanks for checking on that @jgravois.
