### ISSUE TITLE
Simpler build system

### ISSUE THREAD

**Issue by luqmaan** [open-austin/atx-citysdk-js#7]
The current build system requires you to globally install gulp first and then you need to run gulp and webpack separately to get things to run.

We need something that is as simple as:

```
npm install
npm start
```

**Comment by mateoclarke** [comment]
:+1:

**Comment by jgravois** [comment]
:+1:

extreme bonus points if we could find a way to drop the compass dependency too.  i'm not sure what the problem was last night, but i couldn't get it to install anywhere other than my user directory and i've heard ruby on windows is an even tougher nut to crack.

i don't know a damn thing about SASS/CSS, but i know we use node tools exclusively to build the [website](http://esri.github.io/esri-leaflet) for [esri-leaflet](https://github.com/Esri/esri-leaflet/blob/master/package.json#L45).  so hopefully, gulp itself has something comparable to `grunt-sass` :cake:?

**Comment by luqmaan** [comment]
https://www.npmjs.com/package/node-sass

**Comment by luqmaan** [comment]
I started on it here https://github.com/open-austin/austin-park-equity/pull/49. No more compass. :fire:

**Comment by jgravois** [comment]
nice work @luqmaan! i'm happy to log a PR here with comparable changes unless doing something else would be more convenient.

**Comment by mateoclarke** [comment]
Hey @jgravois, do you still want to do this? I feel like it'd be better if you focus on the park geometry tasks and I can knock out this more remedial task. That cool?

**Comment by jgravois** [comment]
i'm happy to stick to the park geometry tasks. i'm flying up to Oakland tomorrow morning, but i'll try and find time to get into it before the afternoon.
